server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /courts {
        proxy_pass http://court-service:8001/courts;
    }

    location /matches {
        proxy_pass http://match-service:8002/matches;
    }
}